#!/usr/bin/env perl
# @(#)$Ident: .gitcommit-msg 2013-04-05 12:10 pjf ;

use strict;
use warnings;
use version; our $VERSION = qv( '0.1' );

use English qw(-no_match_vars);

my $msgf = $ARGV[ 0 ]; my $file = -f 'Changes' ? 'Changes' : undef;

if (defined $file) {
   open my $in, '<', $file or die "File ${file} cannot open: ${OS_ERROR}";

   my $changes = do { local $RS = undef; <$in> }; close $in;
   my ($entry) = $changes =~ m{ [\n][\n] (.*?) [\n][\n] }msx;
   my ($ver)   = $changes =~ m{ ^ (v?[0-9._]+) }mx;

   if ($entry) {
      my $line = (grep { m{ \A [ ] }mx } split m{ [\n] }mx, $entry)[ 0 ] || q();

      $line =~ s{ ^ [ ]+ }{}gmsx; my $msg = substr "${ver} ${line}", 0, 44;

      open my $out, '>', $msgf or die "Path ${msgf} cannot open: ${OS_ERROR}";
      print {$out} $msg; close $out;
   }
}

exit 0;
